-- EverTide OS seed — part 4 of 4: milestones, KPIs, folders, goal, RACI.
-- Paste into the Supabase SQL Editor and Run. Run parts IN ORDER. Idempotent.
-- (Generated by scripts/generate-sql.ts — do not edit.)

do $seed$
declare
  v_org uuid;
  v_site uuid;
  v_project uuid;
  v_task uuid;
  v_user uuid;
begin
  select id into v_org from public.organizations where slug = 'evertide-infusion';
  select id into v_site from public.sites where organization_id = v_org and slug = 'jacksonville-1';

  if not exists (select 1 from public.milestones where site_id = v_site and title = 'Lease executed') then
    insert into public.milestones (organization_id, site_id, title, target_date, gate_criteria, owner_id, status)
    values (v_org, v_site, 'Lease executed', '2026-07-28', 'Signed lease; TI delivery date confirmed in writing',
            (select id from public.profiles where email = 'shlomo@evertide.example'), 'pending');
  end if;

  if not exists (select 1 from public.milestones where site_id = v_site and title = 'AHCA licensure application filed') then
    insert into public.milestones (organization_id, site_id, title, target_date, gate_criteria, owner_id, status)
    values (v_org, v_site, 'AHCA licensure application filed', '2026-08-21', 'Pathway confirmed by counsel; complete application submitted',
            (select id from public.profiles where email = 'shlomo@evertide.example'), 'pending');
  end if;

  if not exists (select 1 from public.milestones where site_id = v_site and title = 'All payer credentialing submitted') then
    insert into public.milestones (organization_id, site_id, title, target_date, gate_criteria, owner_id, status)
    values (v_org, v_site, 'All payer credentialing submitted', '2026-09-04', 'Every target payer application in, same week, tracked weekly',
            (select id from public.profiles where email = 'aaron@evertide.example'), 'pending');
  end if;

  if not exists (select 1 from public.milestones where site_id = v_site and title = 'Construction start') then
    insert into public.milestones (organization_id, site_id, title, target_date, gate_criteria, owner_id, status)
    values (v_org, v_site, 'Construction start', '2026-09-14', 'Permits pulled; GC contract executed',
            (select id from public.profiles where email = 'mordechai@evertide.example'), 'pending');
  end if;

  if not exists (select 1 from public.milestones where site_id = v_site and title = 'EMR platform contracted') then
    insert into public.milestones (organization_id, site_id, title, target_date, gate_criteria, owner_id, status)
    values (v_org, v_site, 'EMR platform contracted', '2026-09-18', 'Vendor signed; implementation plan with dates',
            (select id from public.profiles where email = 'mordechai@evertide.example'), 'pending');
  end if;

  if not exists (select 1 from public.milestones where site_id = v_site and title = 'Lead RN hired') then
    insert into public.milestones (organization_id, site_id, title, target_date, gate_criteria, owner_id, status)
    values (v_org, v_site, 'Lead RN hired', '2026-11-13', 'Offer accepted; start date ≥4 weeks pre-open',
            (select id from public.profiles where email = 'shlomo@evertide.example'), 'pending');
  end if;

  if not exists (select 1 from public.milestones where site_id = v_site and title = 'Construction substantially complete') then
    insert into public.milestones (organization_id, site_id, title, target_date, gate_criteria, owner_id, status)
    values (v_org, v_site, 'Construction substantially complete', '2026-11-20', 'Punch list only; CO path clear',
            (select id from public.profiles where email = 'mordechai@evertide.example'), 'pending');
  end if;

  if not exists (select 1 from public.milestones where site_id = v_site and title = 'First payer contract effective') then
    insert into public.milestones (organization_id, site_id, title, target_date, gate_criteria, owner_id, status)
    values (v_org, v_site, 'First payer contract effective', '2026-12-11', 'At least one major commercial payer live; 2+ preferred',
            (select id from public.profiles where email = 'aaron@evertide.example'), 'pending');
  end if;

  if not exists (select 1 from public.milestones where site_id = v_site and title = 'Drugs on shelf') then
    insert into public.milestones (organization_id, site_id, title, target_date, gate_criteria, owner_id, status)
    values (v_org, v_site, 'Drugs on shelf', '2026-12-18', 'Wholesaler accounts live; formulary v1 stocked; cold chain verified',
            (select id from public.profiles where email = 'aaron@evertide.example'), 'pending');
  end if;

  if not exists (select 1 from public.milestones where site_id = v_site and title = 'Mock infusion days complete') then
    insert into public.milestones (organization_id, site_id, title, target_date, gate_criteria, owner_id, status)
    values (v_org, v_site, 'Mock infusion days complete', '2026-12-31', '2 dry runs done; defect log closed',
            (select id from public.profiles where email = 'zev@evertide.example'), 'pending');
  end if;

  if not exists (select 1 from public.milestones where site_id = v_site and title = 'Go/no-go readiness sign-off') then
    insert into public.milestones (organization_id, site_id, title, target_date, gate_criteria, owner_id, status)
    values (v_org, v_site, 'Go/no-go readiness sign-off', '2027-01-01', 'Licensure + payers + staff + drugs + EMR all green',
            (select id from public.profiles where email = 'shlomo@evertide.example'), 'pending');
  end if;

  if not exists (select 1 from public.milestones where site_id = v_site and title = 'OPENING DAY') then
    insert into public.milestones (organization_id, site_id, title, target_date, gate_criteria, owner_id, status)
    values (v_org, v_site, 'OPENING DAY', '2027-01-04', 'First patient infused',
            (select id from public.profiles where email = 'shlomo@evertide.example'), 'pending');
  end if;

  insert into public.kpis (organization_id, site_id, category, name, description, unit, frequency, owner_id,
                          direction, target_value, green_min, green_max, yellow_min, yellow_max, active, sort_order)
  values (v_org, v_site, 'Financial', 'Cash runway', 'Unrestricted cash divided by current forecast monthly cash burn.', 'months', 'weekly',
          (select id from public.profiles where email = 'shlomo@evertide.example'), 'higher_is_better', 6,
          6, null, 4, null, true, 1)
  on conflict (site_id, name) do nothing;

  insert into public.kpis (organization_id, site_id, category, name, description, unit, frequency, owner_id,
                          direction, target_value, green_min, green_max, yellow_min, yellow_max, active, sort_order)
  values (v_org, v_site, 'Financial', 'Opening budget variance', 'Actual plus committed opening spend versus approved opening budget. Zero or below is green.', 'percent', 'weekly',
          (select id from public.profiles where email = 'aaron@evertide.example'), 'lower_is_better', 0,
          null, 0, null, 5, true, 2)
  on conflict (site_id, name) do nothing;

  insert into public.kpis (organization_id, site_id, category, name, description, unit, frequency, owner_id,
                          direction, target_value, green_min, green_max, yellow_min, yellow_max, active, sort_order)
  values (v_org, v_site, 'Operations', 'Roadmap completion', 'Weighted percent complete across all opening tasks. Dashboard also compares actual to planned completion by date.', 'percent', 'weekly',
          (select id from public.profiles where email = 'mordechai@evertide.example'), 'higher_is_better', 100,
          95, null, 85, null, true, 3)
  on conflict (site_id, name) do nothing;

  insert into public.kpis (organization_id, site_id, category, name, description, unit, frequency, owner_id,
                          direction, target_value, green_min, green_max, yellow_min, yellow_max, active, sort_order)
  values (v_org, v_site, 'Operations', 'Construction completion', 'GC-reported percent complete, supported by weekly photo/update.', 'percent', 'weekly',
          (select id from public.profiles where email = 'mordechai@evertide.example'), 'higher_is_better', 100,
          95, null, 85, null, true, 4)
  on conflict (site_id, name) do nothing;

  insert into public.kpis (organization_id, site_id, category, name, description, unit, frequency, owner_id,
                          direction, target_value, green_min, green_max, yellow_min, yellow_max, active, sort_order)
  values (v_org, v_site, 'Operations', 'Open blockers', 'Number of unresolved blocked tasks and high-priority issues.', 'count', 'weekly',
          (select id from public.profiles where email = 'shlomo@evertide.example'), 'lower_is_better', 0,
          null, 0, null, 2, true, 5)
  on conflict (site_id, name) do nothing;

  insert into public.kpis (organization_id, site_id, category, name, description, unit, frequency, owner_id,
                          direction, target_value, green_min, green_max, yellow_min, yellow_max, active, sort_order)
  values (v_org, v_site, 'Operations', 'Stale in-progress tasks', 'In-progress tasks with no attributed update for seven or more days.', 'count', 'weekly',
          (select id from public.profiles where email = 'shlomo@evertide.example'), 'lower_is_better', 0,
          null, 0, null, 3, true, 6)
  on conflict (site_id, name) do nothing;

  insert into public.kpis (organization_id, site_id, category, name, description, unit, frequency, owner_id,
                          direction, target_value, green_min, green_max, yellow_min, yellow_max, active, sort_order)
  values (v_org, v_site, 'Clinical', 'Clinical readiness checklist', 'Completion of protocols, emergency readiness, consents, competencies, and mock-day prerequisites.', 'percent', 'weekly',
          (select id from public.profiles where email = 'zev@evertide.example'), 'higher_is_better', 100,
          100, null, 80, null, true, 7)
  on conflict (site_id, name) do nothing;

  insert into public.kpis (organization_id, site_id, category, name, description, unit, frequency, owner_id,
                          direction, target_value, green_min, green_max, yellow_min, yellow_max, active, sort_order)
  values (v_org, v_site, 'Clinical', 'Staffing readiness', 'Required opening roles accepted, cleared, onboarded, and competency-ready.', 'percent', 'weekly',
          (select id from public.profiles where email = 'shlomo@evertide.example'), 'higher_is_better', 100,
          100, null, 80, null, true, 8)
  on conflict (site_id, name) do nothing;

  insert into public.kpis (organization_id, site_id, category, name, description, unit, frequency, owner_id,
                          direction, target_value, green_min, green_max, yellow_min, yellow_max, active, sort_order)
  values (v_org, v_site, 'Growth', 'Effective payer contracts', 'Payer contracts with an effective date on or before opening and operationally loaded.', 'count', 'weekly',
          (select id from public.profiles where email = 'aaron@evertide.example'), 'higher_is_better', 2,
          2, null, 1, null, true, 9)
  on conflict (site_id, name) do nothing;

  insert into public.kpis (organization_id, site_id, category, name, description, unit, frequency, owner_id,
                          direction, target_value, green_min, green_max, yellow_min, yellow_max, active, sort_order)
  values (v_org, v_site, 'Growth', 'Referral offices engaged', 'Distinct target practices with a documented substantive outreach interaction.', 'count', 'weekly',
          (select id from public.profiles where email = 'jared@evertide.example'), 'higher_is_better', 25,
          25, null, 15, null, true, 10)
  on conflict (site_id, name) do nothing;

  insert into public.kpis (organization_id, site_id, category, name, description, unit, frequency, owner_id,
                          direction, target_value, green_min, green_max, yellow_min, yellow_max, active, sort_order)
  values (v_org, v_site, 'Growth', 'Committed patient referrals', 'Documented pre-opening patient referrals expected to schedule in opening week.', 'count', 'weekly',
          (select id from public.profiles where email = 'jared@evertide.example'), 'higher_is_better', 10,
          10, null, 5, null, true, 11)
  on conflict (site_id, name) do nothing;

  if not exists (select 1 from public.document_folders where organization_id = v_org and site_id is null and parent_folder_id is null and name = 'Legal & Corporate') then
    insert into public.document_folders (organization_id, name, sort_order) values (v_org, 'Legal & Corporate', 1);
  end if;

  if not exists (select 1 from public.document_folders where organization_id = v_org and site_id is null and parent_folder_id is null and name = 'Lease & Real Estate') then
    insert into public.document_folders (organization_id, name, sort_order) values (v_org, 'Lease & Real Estate', 2);
  end if;

  if not exists (select 1 from public.document_folders where organization_id = v_org and site_id is null and parent_folder_id is null and name = 'Licensure & Regulatory') then
    insert into public.document_folders (organization_id, name, sort_order) values (v_org, 'Licensure & Regulatory', 3);
  end if;

  if not exists (select 1 from public.document_folders where organization_id = v_org and site_id is null and parent_folder_id is null and name = 'Payers & Credentialing') then
    insert into public.document_folders (organization_id, name, sort_order) values (v_org, 'Payers & Credentialing', 4);
  end if;

  if not exists (select 1 from public.document_folders where organization_id = v_org and site_id is null and parent_folder_id is null and name = 'Pharmacy & Drug Supply') then
    insert into public.document_folders (organization_id, name, sort_order) values (v_org, 'Pharmacy & Drug Supply', 5);
  end if;

  if not exists (select 1 from public.document_folders where organization_id = v_org and site_id is null and parent_folder_id is null and name = 'Clinical & Quality') then
    insert into public.document_folders (organization_id, name, sort_order) values (v_org, 'Clinical & Quality', 6);
  end if;

  if not exists (select 1 from public.document_folders where organization_id = v_org and site_id is null and parent_folder_id is null and name = 'Staffing & HR') then
    insert into public.document_folders (organization_id, name, sort_order) values (v_org, 'Staffing & HR', 7);
  end if;

  if not exists (select 1 from public.document_folders where organization_id = v_org and site_id is null and parent_folder_id is null and name = 'Systems & Technology') then
    insert into public.document_folders (organization_id, name, sort_order) values (v_org, 'Systems & Technology', 8);
  end if;

  if not exists (select 1 from public.document_folders where organization_id = v_org and site_id is null and parent_folder_id is null and name = 'Finance') then
    insert into public.document_folders (organization_id, name, sort_order) values (v_org, 'Finance', 9);
  end if;

  if not exists (select 1 from public.document_folders where organization_id = v_org and site_id is null and parent_folder_id is null and name = 'Referral Development & Marketing') then
    insert into public.document_folders (organization_id, name, sort_order) values (v_org, 'Referral Development & Marketing', 10);
  end if;

  if not exists (select 1 from public.document_folders where organization_id = v_org and site_id is null and parent_folder_id is null and name = 'Meetings & Decisions') then
    insert into public.document_folders (organization_id, name, sort_order) values (v_org, 'Meetings & Decisions', 11);
  end if;

  if not exists (select 1 from public.document_folders where organization_id = v_org and site_id is null and parent_folder_id is null and name = 'SOPs & Policies') then
    insert into public.document_folders (organization_id, name, sort_order) values (v_org, 'SOPs & Policies', 12);
  end if;

  if not exists (select 1 from public.goals where site_id = v_site and title = 'Open Jacksonville Site 1 safely and successfully by January 4, 2027') then
    insert into public.goals (organization_id, site_id, title, goal_type, owner_id, start_date, due_date, status, success_criteria)
    values (v_org, v_site, 'Open Jacksonville Site 1 safely and successfully by January 4, 2027', 'annual',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-07-17', '2027-01-04', 'active', 'Licensure in hand, at least 2 payer contracts effective, staff credentialed, drugs on shelf, EMR live, first patient infused on January 4, 2027.');
  end if;

  if not exists (select 1 from public.raci_entries where site_id = v_site and workstream = 'Lease, Legal & Corporate') then
    insert into public.raci_entries (organization_id, site_id, workstream, assignments, sort_order)
    values (v_org, v_site, 'Lease, Legal & Corporate', '{"Shlomo":"A","Jared Friedman":"C","Dr. Zev Neurwith":"I","Mordechai Neurwith":"R","Aaron Jacobs":"C","Richard Hunt":"I"}'::jsonb, 1);
  end if;

  if not exists (select 1 from public.raci_entries where site_id = v_site and workstream = 'Licensure & Regulatory') then
    insert into public.raci_entries (organization_id, site_id, workstream, assignments, sort_order)
    values (v_org, v_site, 'Licensure & Regulatory', '{"Shlomo":"A","Jared Friedman":"I","Dr. Zev Neurwith":"R","Mordechai Neurwith":"R","Aaron Jacobs":"C","Richard Hunt":"I"}'::jsonb, 2);
  end if;

  if not exists (select 1 from public.raci_entries where site_id = v_site and workstream = 'Buildout & Facility') then
    insert into public.raci_entries (organization_id, site_id, workstream, assignments, sort_order)
    values (v_org, v_site, 'Buildout & Facility', '{"Shlomo":"A","Jared Friedman":"C","Dr. Zev Neurwith":"C","Mordechai Neurwith":"R","Aaron Jacobs":"I","Richard Hunt":"C"}'::jsonb, 3);
  end if;

  if not exists (select 1 from public.raci_entries where site_id = v_site and workstream = 'Payer Contracting & Credentialing') then
    insert into public.raci_entries (organization_id, site_id, workstream, assignments, sort_order)
    values (v_org, v_site, 'Payer Contracting & Credentialing', '{"Shlomo":"I","Jared Friedman":"A","Dr. Zev Neurwith":"C","Mordechai Neurwith":"I","Aaron Jacobs":"R","Richard Hunt":"C"}'::jsonb, 4);
  end if;

  if not exists (select 1 from public.raci_entries where site_id = v_site and workstream = 'Pharmacy & Drug Supply') then
    insert into public.raci_entries (organization_id, site_id, workstream, assignments, sort_order)
    values (v_org, v_site, 'Pharmacy & Drug Supply', '{"Shlomo":"I","Jared Friedman":"C","Dr. Zev Neurwith":"A","Mordechai Neurwith":"R","Aaron Jacobs":"R","Richard Hunt":"I"}'::jsonb, 5);
  end if;

  if not exists (select 1 from public.raci_entries where site_id = v_site and workstream = 'Clinical Protocols & Quality') then
    insert into public.raci_entries (organization_id, site_id, workstream, assignments, sort_order)
    values (v_org, v_site, 'Clinical Protocols & Quality', '{"Shlomo":"I","Jared Friedman":"C","Dr. Zev Neurwith":"A","Mordechai Neurwith":"R","Aaron Jacobs":"I","Richard Hunt":"I"}'::jsonb, 6);
  end if;

  if not exists (select 1 from public.raci_entries where site_id = v_site and workstream = 'Staffing, HR & Onboarding') then
    insert into public.raci_entries (organization_id, site_id, workstream, assignments, sort_order)
    values (v_org, v_site, 'Staffing, HR & Onboarding', '{"Shlomo":"A","Jared Friedman":"C","Dr. Zev Neurwith":"C","Mordechai Neurwith":"R","Aaron Jacobs":"I","Richard Hunt":"I"}'::jsonb, 7);
  end if;

  if not exists (select 1 from public.raci_entries where site_id = v_site and workstream = 'Systems & Technology (EMR/RCM stack)') then
    insert into public.raci_entries (organization_id, site_id, workstream, assignments, sort_order)
    values (v_org, v_site, 'Systems & Technology (EMR/RCM stack)', '{"Shlomo":"I","Jared Friedman":"I","Dr. Zev Neurwith":"C","Mordechai Neurwith":"A","Aaron Jacobs":"R","Richard Hunt":"R"}'::jsonb, 8);
  end if;

  if not exists (select 1 from public.raci_entries where site_id = v_site and workstream = 'RCM, Billing & Prior Auth') then
    insert into public.raci_entries (organization_id, site_id, workstream, assignments, sort_order)
    values (v_org, v_site, 'RCM, Billing & Prior Auth', '{"Shlomo":"I","Jared Friedman":"C","Dr. Zev Neurwith":"C","Mordechai Neurwith":"C","Aaron Jacobs":"A","Richard Hunt":"R"}'::jsonb, 9);
  end if;

  if not exists (select 1 from public.raci_entries where site_id = v_site and workstream = 'Referral Development & Marketing') then
    insert into public.raci_entries (organization_id, site_id, workstream, assignments, sort_order)
    values (v_org, v_site, 'Referral Development & Marketing', '{"Shlomo":"I","Jared Friedman":"A","Dr. Zev Neurwith":"R","Mordechai Neurwith":"C","Aaron Jacobs":"C","Richard Hunt":"R"}'::jsonb, 10);
  end if;

  if not exists (select 1 from public.raci_entries where site_id = v_site and workstream = 'Finance, Budget & Scorecard') then
    insert into public.raci_entries (organization_id, site_id, workstream, assignments, sort_order)
    values (v_org, v_site, 'Finance, Budget & Scorecard', '{"Shlomo":"A","Jared Friedman":"I","Dr. Zev Neurwith":"I","Mordechai Neurwith":"I","Aaron Jacobs":"R","Richard Hunt":"I"}'::jsonb, 11);
  end if;

  if not exists (select 1 from public.raci_entries where site_id = v_site and workstream = 'Culture, Standards & Huddle System') then
    insert into public.raci_entries (organization_id, site_id, workstream, assignments, sort_order)
    values (v_org, v_site, 'Culture, Standards & Huddle System', '{"Shlomo":"A","Jared Friedman":"R","Dr. Zev Neurwith":"C","Mordechai Neurwith":"R","Aaron Jacobs":"I","Richard Hunt":"I"}'::jsonb, 12);
  end if;

end
$seed$;

-- Result check — the numbers on the right should read 60 / 12 / 11 / 15 / 12 / 12 / 6:
select 'tasks' as what, count(*) from public.tasks where legacy_id is not null
union all select 'milestones', count(*) from public.milestones
union all select 'kpis', count(*) from public.kpis
union all select 'projects', count(*) from public.projects
union all select 'folders', count(*) from public.document_folders
union all select 'raci rows', count(*) from public.raci_entries
union all select 'team profiles', count(*) from public.profiles;
