-- EverTide OS seed — part 2 of 4: roadmap tasks 1–30.
-- Paste into the Supabase SQL Editor and Run. Run parts IN ORDER. Idempotent.
-- (Generated by scripts/generate-sql.ts — do not edit.)

do $seed$
declare
  v_org uuid;
  v_site uuid;
  v_project uuid;
  v_task uuid;
  v_user uuid;
begin
  select id into v_org from public.organizations where slug = 'evertide-infusion';
  select id into v_site from public.sites where organization_id = v_org and slug = 'jacksonville-1';

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 1) then
    select id into v_project from public.projects where site_id = v_site and phase = '0 – Lease & Legal Foundation' and workstream = 'Legal & Corporate' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 1, '0 – Lease & Legal Foundation', 'Legal & Corporate', 'Receive final lease redline from counsel; complete final review vs. negotiated terms (TI allowance, commencement, exclusivity)',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-07-17', '2026-07-23', 'in_progress', 50,
            'normal', false, 'Example update: redline received from BMD 7/17; final read scheduled 7/21. — Shlomo', 1)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'jared@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 2) then
    select id into v_project from public.projects where site_id = v_site and phase = '0 – Lease & Legal Foundation' and workstream = 'Legal & Corporate' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 2, '0 – Lease & Legal Foundation', 'Legal & Corporate', 'Execute lease for 7880 Gate Parkway, Suite 201; confirm commencement date & TI delivery conditions in writing',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-07-24', '2026-07-28', 'not_started', 0,
            'normal', false, null, 2)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'jared@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 3) then
    select id into v_project from public.projects where site_id = v_site and phase = '0 – Lease & Legal Foundation' and workstream = 'Legal & Corporate' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 3, '0 – Lease & Legal Foundation', 'Legal & Corporate', 'Finalize HoldCo/SiteCo structure and operating agreements with BMD (Jeana); confirm equity grants (Jared 4%, Zev 5%, Aaron 5%) are papered',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-07-17', '2026-08-14', 'not_started', 0,
            'normal', false, null, 3)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'aaron@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 4) then
    select id into v_project from public.projects where site_id = v_site and phase = '0 – Lease & Legal Foundation' and workstream = 'Legal & Corporate' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 4, '0 – Lease & Legal Foundation', 'Legal & Corporate', 'Confirm ownership structure supports chosen licensure pathway (physician ownership % drives AHCA clinic license vs. exemption)',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-07-20', '2026-07-31', 'not_started', 0,
            'critical', true, 'Gate item — do before AHCA filings', 4)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'zev@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 5) then
    select id into v_project from public.projects where site_id = v_site and phase = '0 – Lease & Legal Foundation' and workstream = 'Legal & Corporate' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 5, '0 – Lease & Legal Foundation', 'Legal & Corporate', 'Bind insurance: general liability, property, workers'' comp, medical malpractice (entity + Zev), cyber',
            (select id from public.profiles where email = 'mordechai@evertide.example'),
            '2026-08-03', '2026-09-04', 'not_started', 0,
            'normal', false, null, 5)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'shlomo@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 6) then
    select id into v_project from public.projects where site_id = v_site and phase = '0 – Lease & Legal Foundation' and workstream = 'Legal & Corporate' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 6, '0 – Lease & Legal Foundation', 'Legal & Corporate', 'Register SiteCo with FL Dept. of Revenue; Duval County local business tax receipt; city registrations',
            (select id from public.profiles where email = 'mordechai@evertide.example'),
            '2026-08-03', '2026-08-21', 'not_started', 0,
            'normal', false, null, 6)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'aaron@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 7) then
    select id into v_project from public.projects where site_id = v_site and phase = '0 – Lease & Legal Foundation' and workstream = 'Legal & Corporate' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 7, '0 – Lease & Legal Foundation', 'Legal & Corporate', 'Medical Director Agreement for Dr. Neurwith (scope, supervision, stipend) executed',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-08-03', '2026-08-28', 'not_started', 0,
            'normal', false, null, 7)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'zev@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 8) then
    select id into v_project from public.projects where site_id = v_site and phase = '1 – Licensure, Enrollment & Credentialing (Long-Lead)' and workstream = 'Licensure & Regulatory' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 8, '1 – Licensure, Enrollment & Credentialing (Long-Lead)', 'Licensure & Regulatory', 'Confirm FL licensure pathway with health care counsel (AHCA Health Care Clinic license vs. exemption certificate) and file application',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-07-20', '2026-08-21', 'not_started', 0,
            'critical', true, 'CRITICAL PATH — AHCA processing can run 60–90+ days', 8)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'zev@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 9) then
    select id into v_project from public.projects where site_id = v_site and phase = '1 – Licensure, Enrollment & Credentialing (Long-Lead)' and workstream = 'Licensure & Regulatory' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 9, '1 – Licensure, Enrollment & Credentialing (Long-Lead)', 'Licensure & Regulatory', 'Obtain Type 2 NPI for SiteCo; confirm taxonomy codes',
            (select id from public.profiles where email = 'aaron@evertide.example'),
            '2026-07-27', '2026-08-07', 'not_started', 0,
            'normal', false, null, 9)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 10) then
    select id into v_project from public.projects where site_id = v_site and phase = '1 – Licensure, Enrollment & Credentialing (Long-Lead)' and workstream = 'Licensure & Regulatory' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 10, '1 – Licensure, Enrollment & Credentialing (Long-Lead)', 'Licensure & Regulatory', 'DEA registration for Jacksonville location (if controlled substances stocked); FL dispensing/office-use compliance review',
            (select id from public.profiles where email = 'zev@evertide.example'),
            '2026-08-10', '2026-09-18', 'not_started', 0,
            'normal', false, null, 10)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 11) then
    select id into v_project from public.projects where site_id = v_site and phase = '1 – Licensure, Enrollment & Credentialing (Long-Lead)' and workstream = 'Licensure & Regulatory' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 11, '1 – Licensure, Enrollment & Credentialing (Long-Lead)', 'Licensure & Regulatory', 'CLIA Certificate of Waiver (point-of-care labs) application',
            (select id from public.profiles where email = 'zev@evertide.example'),
            '2026-08-17', '2026-09-25', 'not_started', 0,
            'normal', false, null, 11)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 12) then
    select id into v_project from public.projects where site_id = v_site and phase = '1 – Licensure, Enrollment & Credentialing (Long-Lead)' and workstream = 'Licensure & Regulatory' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 12, '1 – Licensure, Enrollment & Credentialing (Long-Lead)', 'Licensure & Regulatory', 'Medicare enrollment decision + PECOS 855B filing if pursuing Part B buy-and-bill',
            (select id from public.profiles where email = 'aaron@evertide.example'),
            '2026-08-03', '2026-09-11', 'not_started', 0,
            'normal', false, 'Decide before payer contracting sequencing', 12)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'zev@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 13) then
    select id into v_project from public.projects where site_id = v_site and phase = '1 – Licensure, Enrollment & Credentialing (Long-Lead)' and workstream = 'Licensure & Regulatory' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 13, '1 – Licensure, Enrollment & Credentialing (Long-Lead)', 'Licensure & Regulatory', 'Verify Zev''s FL license, board status, malpractice history docs packaged for all credentialing files',
            (select id from public.profiles where email = 'aaron@evertide.example'),
            '2026-07-27', '2026-08-07', 'not_started', 0,
            'normal', false, null, 13)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'zev@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 14) then
    select id into v_project from public.projects where site_id = v_site and phase = '1 – Licensure, Enrollment & Credentialing (Long-Lead)' and workstream = 'Licensure & Regulatory' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 14, '1 – Licensure, Enrollment & Credentialing (Long-Lead)', 'Licensure & Regulatory', 'OSHA/bloodborne pathogen, biohazard waste hauler contract, sharps program',
            (select id from public.profiles where email = 'mordechai@evertide.example'),
            '2026-10-05', '2026-11-13', 'not_started', 0,
            'normal', false, null, 14)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'zev@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 15) then
    select id into v_project from public.projects where site_id = v_site and phase = '1 – Licensure, Enrollment & Credentialing (Long-Lead)' and workstream = 'Licensure & Regulatory' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 15, '1 – Licensure, Enrollment & Credentialing (Long-Lead)', 'Licensure & Regulatory', 'Fire marshal inspection & certificate of occupancy coordination with GC',
            (select id from public.profiles where email = 'mordechai@evertide.example'),
            '2026-11-02', '2026-12-04', 'not_started', 0,
            'normal', false, null, 15)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'shlomo@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 16) then
    select id into v_project from public.projects where site_id = v_site and phase = '2 – Buildout & Facility' and workstream = 'Buildout & Facility' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 16, '2 – Buildout & Facility', 'Buildout & Facility', 'Finalize space plan & TI construction drawings (infusion bays, med room, waiting, ADA)',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-07-27', '2026-08-21', 'not_started', 0,
            'normal', false, null, 16)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 17) then
    select id into v_project from public.projects where site_id = v_site and phase = '2 – Buildout & Facility' and workstream = 'Buildout & Facility' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 17, '2 – Buildout & Facility', 'Buildout & Facility', 'Select GC, execute construction contract, pull permits',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-08-17', '2026-09-11', 'not_started', 0,
            'normal', false, null, 17)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 18) then
    select id into v_project from public.projects where site_id = v_site and phase = '2 – Buildout & Facility' and workstream = 'Buildout & Facility' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 18, '2 – Buildout & Facility', 'Buildout & Facility', 'TI construction — demo through final punch list',
            (select id from public.profiles where email = 'mordechai@evertide.example'),
            '2026-09-14', '2026-11-20', 'not_started', 0,
            'normal', false, 'Weekly GC check-in; photos to huddle', 18)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'shlomo@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 19) then
    select id into v_project from public.projects where site_id = v_site and phase = '2 – Buildout & Facility' and workstream = 'Buildout & Facility' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 19, '2 – Buildout & Facility', 'Buildout & Facility', 'Order long-lead FF&E: infusion chairs, recliners, IV poles, med refrigerator w/ continuous temp monitoring, emergency cart',
            (select id from public.profiles where email = 'mordechai@evertide.example'),
            '2026-08-24', '2026-10-16', 'not_started', 0,
            'normal', false, null, 19)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'zev@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 20) then
    select id into v_project from public.projects where site_id = v_site and phase = '2 – Buildout & Facility' and workstream = 'Buildout & Facility' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 20, '2 – Buildout & Facility', 'Buildout & Facility', 'IT infrastructure: internet, network, phones, fax, security cameras, access control',
            (select id from public.profiles where email = 'mordechai@evertide.example'),
            '2026-10-05', '2026-11-13', 'not_started', 0,
            'normal', false, null, 20)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'richard@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 21) then
    select id into v_project from public.projects where site_id = v_site and phase = '2 – Buildout & Facility' and workstream = 'Buildout & Facility' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 21, '2 – Buildout & Facility', 'Buildout & Facility', 'Interior branding & exterior signage (landlord + city approval)',
            (select id from public.profiles where email = 'jared@evertide.example'),
            '2026-09-07', '2026-11-06', 'not_started', 0,
            'normal', false, null, 21)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 22) then
    select id into v_project from public.projects where site_id = v_site and phase = '2 – Buildout & Facility' and workstream = 'Buildout & Facility' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 22, '2 – Buildout & Facility', 'Buildout & Facility', 'Furniture, TVs, wifi for patients, coffee/snack station — patient experience walkthrough (Schulze standards)',
            (select id from public.profiles where email = 'mordechai@evertide.example'),
            '2026-11-09', '2026-12-04', 'not_started', 0,
            'normal', false, null, 22)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'jared@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 23) then
    select id into v_project from public.projects where site_id = v_site and phase = '2 – Buildout & Facility' and workstream = 'Buildout & Facility' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 23, '2 – Buildout & Facility', 'Buildout & Facility', 'Final deep clean, life-safety checks, mock patient walk-through of full visit journey',
            (select id from public.profiles where email = 'mordechai@evertide.example'),
            '2026-12-07', '2026-12-18', 'not_started', 0,
            'normal', false, null, 23)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'zev@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 24) then
    select id into v_project from public.projects where site_id = v_site and phase = '3 – Payers, Pharmacy & RCM' and workstream = 'Payer Contracting' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 24, '3 – Payers, Pharmacy & RCM', 'Payer Contracting', 'Finalize target payer list & contracting strategy (FL Blue, UHC, Aetna, Cigna, Medicare; Medicaid decision)',
            (select id from public.profiles where email = 'jared@evertide.example'),
            '2026-07-27', '2026-08-14', 'not_started', 0,
            'normal', false, 'Gating condition from go/no-go', 24)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'aaron@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 25) then
    select id into v_project from public.projects where site_id = v_site and phase = '3 – Payers, Pharmacy & RCM' and workstream = 'Payer Contracting' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 25, '3 – Payers, Pharmacy & RCM', 'Payer Contracting', 'Submit credentialing applications for Dr. Neurwith + facility to all target payers',
            (select id from public.profiles where email = 'aaron@evertide.example'),
            '2026-08-17', '2026-09-04', 'not_started', 0,
            'critical', true, 'CRITICAL PATH — 90–150 day cycles; submit everything same week', 25)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'jared@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 26) then
    select id into v_project from public.projects where site_id = v_site and phase = '3 – Payers, Pharmacy & RCM' and workstream = 'Payer Contracting' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 26, '3 – Payers, Pharmacy & RCM', 'Payer Contracting', 'Weekly credentialing status tracker & payer follow-up call cadence',
            (select id from public.profiles where email = 'aaron@evertide.example'),
            '2026-09-07', '2026-12-31', 'not_started', 0,
            'normal', false, 'Standing agenda item at weekly huddle', 26)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'richard@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 27) then
    select id into v_project from public.projects where site_id = v_site and phase = '3 – Payers, Pharmacy & RCM' and workstream = 'Payer Contracting' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 27, '3 – Payers, Pharmacy & RCM', 'Payer Contracting', 'Negotiate fee schedules; model reimbursement vs. drug acquisition cost per top 15 J-codes',
            (select id from public.profiles where email = 'aaron@evertide.example'),
            '2026-10-05', '2026-12-11', 'not_started', 0,
            'normal', false, null, 27)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'jared@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 28) then
    select id into v_project from public.projects where site_id = v_site and phase = '3 – Payers, Pharmacy & RCM' and workstream = 'Pharmacy & Drug Supply' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 28, '3 – Payers, Pharmacy & RCM', 'Pharmacy & Drug Supply', 'Open wholesaler/specialty distributor accounts (Cencora, McKesson); credit terms & drug float sized',
            (select id from public.profiles where email = 'aaron@evertide.example'),
            '2026-09-07', '2026-10-23', 'not_started', 0,
            'normal', false, null, 28)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'shlomo@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 29) then
    select id into v_project from public.projects where site_id = v_site and phase = '3 – Payers, Pharmacy & RCM' and workstream = 'Pharmacy & Drug Supply' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 29, '3 – Payers, Pharmacy & RCM', 'Pharmacy & Drug Supply', 'Formulary v1: target therapies (biologics for rheum/GI/neuro/derm), NDC list, par levels, cold-chain SOP',
            (select id from public.profiles where email = 'zev@evertide.example'),
            '2026-09-21', '2026-11-06', 'not_started', 0,
            'normal', false, null, 29)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'aaron@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 30) then
    select id into v_project from public.projects where site_id = v_site and phase = '3 – Payers, Pharmacy & RCM' and workstream = 'Pharmacy & Drug Supply' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 30, '3 – Payers, Pharmacy & RCM', 'Pharmacy & Drug Supply', 'Inventory management workflow in infusion platform; receiving, lot/expiry tracking, waste documentation',
            (select id from public.profiles where email = 'mordechai@evertide.example'),
            '2026-11-02', '2026-12-04', 'not_started', 0,
            'normal', false, null, 30)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'aaron@evertide.example')) on conflict do nothing;
  end if;

end
$seed$;
