-- EverTide OS seed — part 3 of 4: roadmap tasks 31–60.
-- Paste into the Supabase SQL Editor and Run. Run parts IN ORDER. Idempotent.
-- (Generated by scripts/generate-sql.ts — do not edit.)

do $seed$
declare
  v_org uuid;
  v_site uuid;
  v_project uuid;
  v_task uuid;
  v_user uuid;
begin
  select id into v_org from public.organizations where slug = 'evertide-infusion';
  select id into v_site from public.sites where organization_id = v_org and slug = 'jacksonville-1';

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 31) then
    select id into v_project from public.projects where site_id = v_site and phase = '3 – Payers, Pharmacy & RCM' and workstream = 'RCM & Billing' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 31, '3 – Payers, Pharmacy & RCM', 'RCM & Billing', 'Design end-to-end RCM workflow: referral intake → benefits investigation → prior auth → scheduling → charge capture → claim → AR follow-up',
            (select id from public.profiles where email = 'aaron@evertide.example'),
            '2026-08-24', '2026-10-02', 'not_started', 0,
            'normal', false, null, 31)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 32) then
    select id into v_project from public.projects where site_id = v_site and phase = '3 – Payers, Pharmacy & RCM' and workstream = 'RCM & Billing' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 32, '3 – Payers, Pharmacy & RCM', 'RCM & Billing', 'Clearinghouse, billing platform, charge master (J-codes, admin codes 96365–96417), payer-specific edits',
            (select id from public.profiles where email = 'aaron@evertide.example'),
            '2026-10-05', '2026-11-13', 'not_started', 0,
            'normal', false, null, 32)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'richard@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 33) then
    select id into v_project from public.projects where site_id = v_site and phase = '3 – Payers, Pharmacy & RCM' and workstream = 'RCM & Billing' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 33, '3 – Payers, Pharmacy & RCM', 'RCM & Billing', 'Copay assistance / manufacturer program enrollment playbook (per-drug foundations, hub services)',
            (select id from public.profiles where email = 'aaron@evertide.example'),
            '2026-10-19', '2026-11-20', 'not_started', 0,
            'normal', false, null, 33)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'jared@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 34) then
    select id into v_project from public.projects where site_id = v_site and phase = '3 – Payers, Pharmacy & RCM' and workstream = 'RCM & Billing' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 34, '3 – Payers, Pharmacy & RCM', 'RCM & Billing', 'Financial policy, patient cost estimate script, and financial counseling SOP',
            (select id from public.profiles where email = 'aaron@evertide.example'),
            '2026-11-09', '2026-12-04', 'not_started', 0,
            'normal', false, null, 34)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 35) then
    select id into v_project from public.projects where site_id = v_site and phase = '4 – Clinical, Staffing & Systems' and workstream = 'Clinical Operations' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 35, '4 – Clinical, Staffing & Systems', 'Clinical Operations', 'Clinical protocol library: standing orders per therapy, infusion rates, pre-meds, monitoring parameters',
            (select id from public.profiles where email = 'zev@evertide.example'),
            '2026-09-07', '2026-11-06', 'not_started', 0,
            'normal', false, null, 35)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'jared@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 36) then
    select id into v_project from public.projects where site_id = v_site and phase = '4 – Clinical, Staffing & Systems' and workstream = 'Clinical Operations' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 36, '4 – Clinical, Staffing & Systems', 'Clinical Operations', 'Emergency protocols: anaphylaxis, infusion reactions, code response, EMS activation; crash kit contents & checks',
            (select id from public.profiles where email = 'zev@evertide.example'),
            '2026-10-05', '2026-11-20', 'not_started', 0,
            'normal', false, null, 36)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 37) then
    select id into v_project from public.projects where site_id = v_site and phase = '4 – Clinical, Staffing & Systems' and workstream = 'Clinical Operations' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 37, '4 – Clinical, Staffing & Systems', 'Clinical Operations', 'Consent forms, patient education materials, adverse event reporting workflow',
            (select id from public.profiles where email = 'zev@evertide.example'),
            '2026-10-19', '2026-11-27', 'not_started', 0,
            'normal', false, null, 37)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 38) then
    select id into v_project from public.projects where site_id = v_site and phase = '4 – Clinical, Staffing & Systems' and workstream = 'Clinical Operations' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 38, '4 – Clinical, Staffing & Systems', 'Clinical Operations', 'Nursing competency checklists & skills validation program (IV access, ports, reaction management)',
            (select id from public.profiles where email = 'zev@evertide.example'),
            '2026-11-02', '2026-12-11', 'not_started', 0,
            'normal', false, null, 38)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 39) then
    select id into v_project from public.projects where site_id = v_site and phase = '4 – Clinical, Staffing & Systems' and workstream = 'Staffing & HR' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 39, '4 – Clinical, Staffing & Systems', 'Staffing & HR', 'Org chart + job descriptions: lead infusion RN, infusion RN(s), intake/benefits coordinator, MA/front desk',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-09-07', '2026-09-25', 'not_started', 0,
            'normal', false, null, 39)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 40) then
    select id into v_project from public.projects where site_id = v_site and phase = '4 – Clinical, Staffing & Systems' and workstream = 'Staffing & HR' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 40, '4 – Clinical, Staffing & Systems', 'Staffing & HR', 'Recruit & hire lead infusion RN (target start ~4 wks pre-open)',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-09-28', '2026-11-13', 'not_started', 0,
            'normal', false, null, 40)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'zev@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 41) then
    select id into v_project from public.projects where site_id = v_site and phase = '4 – Clinical, Staffing & Systems' and workstream = 'Staffing & HR' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 41, '4 – Clinical, Staffing & Systems', 'Staffing & HR', 'Recruit & hire remaining team; background checks, license verification, payroll/benefits setup',
            (select id from public.profiles where email = 'mordechai@evertide.example'),
            '2026-10-12', '2026-12-04', 'not_started', 0,
            'normal', false, null, 41)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'shlomo@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 42) then
    select id into v_project from public.projects where site_id = v_site and phase = '4 – Clinical, Staffing & Systems' and workstream = 'Staffing & HR' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 42, '4 – Clinical, Staffing & Systems', 'Staffing & HR', 'EverTide orientation: culture-first onboarding (Schulze Day 1), standards handbook, service scripts, 90-day competency gate',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-12-07', '2026-12-18', 'not_started', 0,
            'normal', false, null, 42)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 43) then
    select id into v_project from public.projects where site_id = v_site and phase = '4 – Clinical, Staffing & Systems' and workstream = 'Systems & Technology' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 43, '4 – Clinical, Staffing & Systems', 'Systems & Technology', 'Select & contract infusion EMR/workflow platform (e.g., WeInfuse-type); implementation kickoff',
            (select id from public.profiles where email = 'mordechai@evertide.example'),
            '2026-08-24', '2026-09-18', 'not_started', 0,
            'normal', false, null, 43)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'aaron@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 44) then
    select id into v_project from public.projects where site_id = v_site and phase = '4 – Clinical, Staffing & Systems' and workstream = 'Systems & Technology' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 44, '4 – Clinical, Staffing & Systems', 'Systems & Technology', 'Platform build: templates, order sets, scheduling rules, inventory, billing integration; staff training',
            (select id from public.profiles where email = 'mordechai@evertide.example'),
            '2026-09-21', '2026-12-11', 'not_started', 0,
            'normal', false, null, 44)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'aaron@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 45) then
    select id into v_project from public.projects where site_id = v_site and phase = '4 – Clinical, Staffing & Systems' and workstream = 'Systems & Technology' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 45, '4 – Clinical, Staffing & Systems', 'Systems & Technology', 'E-fax/referral intake channel, phone tree, website scheduling request form live',
            (select id from public.profiles where email = 'richard@evertide.example'),
            '2026-10-19', '2026-11-27', 'not_started', 0,
            'normal', false, null, 45)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 46) then
    select id into v_project from public.projects where site_id = v_site and phase = '5 – Referral Development & Marketing' and workstream = 'Referral Development' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 46, '5 – Referral Development & Marketing', 'Referral Development', 'Referral market map: top 50 target prescribers (rheum, GI, neuro, derm) in Jacksonville metro w/ current infusion destination',
            (select id from public.profiles where email = 'jared@evertide.example'),
            '2026-08-10', '2026-09-11', 'not_started', 0,
            'normal', false, null, 46)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'richard@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 47) then
    select id into v_project from public.projects where site_id = v_site and phase = '5 – Referral Development & Marketing' and workstream = 'Referral Development' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 47, '5 – Referral Development & Marketing', 'Referral Development', 'Collateral & referral kit: one-pager, referral form, insurance grid, service pledge',
            (select id from public.profiles where email = 'jared@evertide.example'),
            '2026-09-14', '2026-10-09', 'not_started', 0,
            'normal', false, null, 47)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'richard@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 48) then
    select id into v_project from public.projects where site_id = v_site and phase = '5 – Referral Development & Marketing' and workstream = 'Referral Development' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 48, '5 – Referral Development & Marketing', 'Referral Development', 'Prescriber outreach wave 1 (Zev peer-to-peer + Jared): 25 offices before opening',
            (select id from public.profiles where email = 'jared@evertide.example'),
            '2026-10-12', '2026-12-18', 'not_started', 0,
            'normal', false, 'Track visits & committed referrals weekly', 48)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'zev@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 49) then
    select id into v_project from public.projects where site_id = v_site and phase = '5 – Referral Development & Marketing' and workstream = 'Referral Development' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 49, '5 – Referral Development & Marketing', 'Referral Development', 'Website, Google Business Profile, local SEO live; phone & referral fax tested end-to-end',
            (select id from public.profiles where email = 'jared@evertide.example'),
            '2026-10-19', '2026-11-20', 'not_started', 0,
            'normal', false, null, 49)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'richard@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 50) then
    select id into v_project from public.projects where site_id = v_site and phase = '5 – Referral Development & Marketing' and workstream = 'Referral Development' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 50, '5 – Referral Development & Marketing', 'Referral Development', 'Open house / launch event for referring offices (week before opening)',
            (select id from public.profiles where email = 'jared@evertide.example'),
            '2026-12-14', '2026-12-29', 'not_started', 0,
            'normal', false, null, 50)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 51) then
    select id into v_project from public.projects where site_id = v_site and phase = '5 – Referral Development & Marketing' and workstream = 'Referral Development' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 51, '5 – Referral Development & Marketing', 'Referral Development', 'Secure 10+ committed patient referrals pre-opening; first-week schedule built',
            (select id from public.profiles where email = 'jared@evertide.example'),
            '2026-11-30', '2027-01-01', 'not_started', 0,
            'normal', false, null, 51)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'aaron@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 52) then
    select id into v_project from public.projects where site_id = v_site and phase = '0 – Lease & Legal Foundation' and workstream = 'Finance' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 52, '0 – Lease & Legal Foundation', 'Finance', 'Open SiteCo bank accounts; QuickBooks entity setup; chart of accounts',
            (select id from public.profiles where email = 'aaron@evertide.example'),
            '2026-07-27', '2026-08-14', 'not_started', 0,
            'normal', false, null, 52)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'shlomo@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 53) then
    select id into v_project from public.projects where site_id = v_site and phase = '3 – Payers, Pharmacy & RCM' and workstream = 'Finance' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 53, '3 – Payers, Pharmacy & RCM', 'Finance', 'Working capital plan: drug float sizing, LOC if needed, 6-month cash runway model',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-09-14', '2026-10-16', 'not_started', 0,
            'normal', false, null, 53)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'aaron@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 54) then
    select id into v_project from public.projects where site_id = v_site and phase = '4 – Clinical, Staffing & Systems' and workstream = 'Finance' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 54, '4 – Clinical, Staffing & Systems', 'Finance', 'Opening budget vs. actual tracker; monthly close cadence; KPI scorecard (chair utilization, referral-to-infusion conversion, days to auth, AR days)',
            (select id from public.profiles where email = 'aaron@evertide.example'),
            '2026-11-02', '2026-12-11', 'not_started', 0,
            'normal', false, null, 54)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'shlomo@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 55) then
    select id into v_project from public.projects where site_id = v_site and phase = '6 – Pre-Opening Countdown' and workstream = 'Accountability System' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 55, '6 – Pre-Opening Countdown', 'Accountability System', 'Launch weekly EverTide leadership huddle (Studer): scorecard review, wins, blockers, owner commitments — every Tuesday',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-07-28', '2026-07-28', 'not_started', 0,
            'normal', false, 'Recurs weekly through opening', 55)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 56) then
    select id into v_project from public.projects where site_id = v_site and phase = '6 – Pre-Opening Countdown' and workstream = 'Accountability System' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 56, '6 – Pre-Opening Countdown', 'Accountability System', '30/60/90-day leader plans for Jared, Zev, Mordechai, Aaron tied to this roadmap',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-08-03', '2026-08-14', 'not_started', 0,
            'normal', false, null, 56)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'jared@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 57) then
    select id into v_project from public.projects where site_id = v_site and phase = '6 – Pre-Opening Countdown' and workstream = 'Accountability System' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 57, '6 – Pre-Opening Countdown', 'Accountability System', 'Adapt Armada Excellence Standards Handbook for EverTide (service values, scripts, defect review)',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-09-07', '2026-10-30', 'not_started', 0,
            'normal', false, null, 57)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'jared@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 58) then
    select id into v_project from public.projects where site_id = v_site and phase = '6 – Pre-Opening Countdown' and workstream = 'Pre-Opening' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 58, '6 – Pre-Opening Countdown', 'Pre-Opening', 'Dry-run days: 2 full mock infusion days with staff (check-in → chair → discharge → billing), defect log & fixes',
            (select id from public.profiles where email = 'zev@evertide.example'),
            '2026-12-21', '2026-12-31', 'not_started', 0,
            'normal', false, null, 58)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 59) then
    select id into v_project from public.projects where site_id = v_site and phase = '6 – Pre-Opening Countdown' and workstream = 'Pre-Opening' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 59, '6 – Pre-Opening Countdown', 'Pre-Opening', 'Opening readiness checklist sign-off: licensure, at least 2 payer contracts effective, staff credentialed, drugs on shelf, EMR live',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2026-12-28', '2027-01-01', 'not_started', 0,
            'critical', true, 'Go/no-go gate', 59)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'aaron@evertide.example')) on conflict do nothing;
  end if;

  if not exists (select 1 from public.tasks where site_id = v_site and legacy_id = 60) then
    select id into v_project from public.projects where site_id = v_site and phase = '6 – Pre-Opening Countdown' and workstream = 'Pre-Opening' and archived_at is null;
    insert into public.tasks (organization_id, site_id, project_id, legacy_id, phase, workstream, title, owner_id,
                              start_date, due_date, status, percent_done, priority, critical, notes, sort_order)
    values (v_org, v_site, v_project, 60, '6 – Pre-Opening Countdown', 'Pre-Opening', 'OPENING DAY — first patient infused',
            (select id from public.profiles where email = 'shlomo@evertide.example'),
            '2027-01-04', '2027-01-04', 'not_started', 0,
            'normal', false, 'Target date; slips if AHCA or payer effective dates slip', 60)
    returning id into v_task;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'jared@evertide.example')) on conflict do nothing;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'zev@evertide.example')) on conflict do nothing;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'mordechai@evertide.example')) on conflict do nothing;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'aaron@evertide.example')) on conflict do nothing;
    insert into public.task_helpers (task_id, user_id) values (v_task, (select id from public.profiles where email = 'richard@evertide.example')) on conflict do nothing;
  end if;

end
$seed$;
